import './globals.css'
import type { Metadata } from 'next'

import { Raleway } from 'next/font/google'

const raleway = Raleway({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-raleway'
})

 
export const metadata: Metadata = {
  title: 'Form Fit AI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={`${raleway.className}`} lang="en">
      <body className='leading-normal overflow-x-hidden'>{children}</body>
    </html>
  )
}